### PR TITLE
Add `trim/0`, `ltrim/0` and `rtrim/0`

### PR DESCRIPTION
**Pull request by wader**
Trims leading and trailing whitespace.

Was added to jq in https://github.com/jqlang/jq/pull/3056

### CODE REVIEW

**Comment by wader** [comment]
In the jq version of this there is an optimization to not create a new string if there is nothing to trim https://github.com/jqlang/jq/pull/3056/files#diff-bd792def7de6d4b8d70ddc844eabe52f73c264904e263580215219b669a2ca9cR1239-R1242 i tried to follow the rust code but not sure i understood fully how it would behave

**Comment by wader** [comment]
Thanks 🙏  and nice you added the optimisation, i haven't researched it but i suspect that most calls to trim will not trim anything. Maybe there are more string functions that could benefit of the same optimisation?

**Comment by 01mf02** [comment]
I just checked that, and `ltrimstr` as well as `rtrimstr` already perform this optimisation.
`escape_csv` and `escape_sh` are unfortunately no candidates for this optimisation due to the way that [`str::replace`](https://doc.rust-lang.org/std/primitive.str.html#method.replace) works. The same goes for `ascii_downcase` and `ascii_upcase`.

**Comment by wader** [comment]
👍 now also remembered that i forgot to add tests for some different unicode whitespace codepoints, there is a bunch of different ones, ex a test like this https://github.com/jqlang/jq/blob/master/tests/jq.test#L1363-L1367. I did a quick check and it seems like jq, gojq and jaq all agree on what is whitespace now, ex javascript does not see `U+0085 NEXT LINE` as whitespace.

**Pull request merged**
